### ISSUE TITLE
Not working with snort3

### ISSUE THREAD

**Issue by DigiAngel** [shirkdog/pulledpork3#27]
With LightSpeed selected:
~~~
Downloading ruleset file: Talos_LightSPD.tar.gz from: https://snort.org/rules/Talos_LightSPD.tar.gz?oinkcode=<hidden>
Writing ruleset file to disk: /tmp/PulledPork-2021.07.19-13.40.44/downloaded_rulesets/Talos_LightSPD.tar.gz
Processing LightSPD ruleset
Traceback (most recent call last):
  File "./pulledpork.py", line 937, in <module>
    main()
  File "./pulledpork.py", line 399, in main
    log.verbose(f' - LightSPD Rules:  {registered_rules}')
UnboundLocalError: local variable 'registered_rules' referenced before assignment
~~~

with registered selected:
~~~
Loading configuration file: /opt/snort/etc/pulledpork/pulledpork.conf
Downloading ruleset file: snortrules-snapshot-3160.tar.gz from: https://snort.org/rules/snortrules-snapshot-3160.tar.gz?oinkcode=<hidden>
Traceback (most recent call last):
  File "./pulledpork.py", line 937, in <module>
    main()
  File "./pulledpork.py", line 190, in main
    local_rulesets = download_rulesets(ruleset_urls)
  File "./pulledpork.py", line 788, in download_rulesets
    r.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://snort.org/rules/snortrules-snapshot-3160.tar.gz?oinkcode=<code>
~~~

**Comment by colingrady** [comment]
At least partly fixed w/ latest commits.
I *think* the ruleset download error is because you have a version of Snort later than the versioned ruleset available from the side. You might need to set the Snort version in the config to the latest version ruleset identified on the site.
